/**
 * Provider adapter types — the contract between the source registry and
 * provider-specific URL generation, validation, and response parsing.
 *
 * Adapters are source-aware and method-aware: they operate on SourceRecordV2
 * records, not abstract topics. This lets the same provider (e.g., coingecko)
 * handle different operations (simple-price vs trending) with different logic.
 */

import type { SourceRecordV2 } from "../catalog.js";
import type { ExtractedClaim } from "../../claim-extraction.js";

// ── Attestation Method ──────────────────────────────

export type AttestationMethod = "TLSN" | "DAHR";

// ── Surgical Candidate ──────────────────────────────

/**
 * A targeted URL constructed from a specific claim in the post text.
 * Used by the attestation planner to verify individual facts surgically.
 */
export interface SurgicalCandidate {
  /** The claim this candidate was built for */
  claim: ExtractedClaim;
  /** Fully resolved URL ready to attest */
  url: string;
  /** Estimated response size in bytes */
  estimatedSizeBytes: number;
  /** HTTP method (always GET for attestation) */
  method: "GET";
  /** JSONPath to extract the verifiable value from the response */
  extractionPath: string;
  /** Tolerance for numeric comparison (e.g., 0.02 = 2%) */
  tolerance?: number;
  /** Provider name for attribution */
  provider: string;
  /** Rate limit bucket key for acquireRateLimitToken */
  rateLimitBucket?: string;
}

// ── Candidate Request ───────────────────────────────

/**
 * A concrete fetch request generated by an adapter for a specific source+topic.
 * Represents one URL that can be attested via TLSN or DAHR.
 */
export interface CandidateRequest {
  /** Source record ID from catalog */
  sourceId: string;
  /** Provider name (e.g., "hn-algolia") */
  provider: string;
  /** Operation within this provider (e.g., "search", "trending") */
  operation: string;
  /** HTTP method — always GET for attestation */
  method: "GET";
  /** Fully resolved URL ready to fetch */
  url: string;
  /** Attestation method this URL is safe for */
  attestation: AttestationMethod;
  /** Estimated response size in KB (for TLSN budget checks) */
  estimatedSizeKb?: number;
  /** Hints for downstream matching (key terms from the query) */
  matchHints: string[];
}

// ── Evidence Entry ──────────────────────────────────

/**
 * A structured data entry extracted from a provider response.
 * Replaces the undefined DataEntry type from the original plan.
 * Used by matcher.ts for evidence-based scoring.
 */
export interface EvidenceEntry {
  /** Entry identifier (provider-specific: HN objectID, GitHub repo id, etc.) */
  id: string;
  /** Entry title or headline */
  title?: string;
  /** Brief summary or description */
  summary?: string;
  /** Full text content for claim matching */
  bodyText: string;
  /** Canonical URL to the original content */
  canonicalUrl?: string;
  /** Publication timestamp (ISO 8601) */
  publishedAt?: string;
  /** Topic tags inferred from entry content */
  topics: string[];
  /** Numeric metrics (price, volume, TVL, citations, etc.) */
  metrics?: Record<string, string | number>;
  /** Raw provider response for this entry (for debugging/audit) */
  raw: unknown;
}

// ── Parsed Response ─────────────────────────────────

/**
 * Result of adapter.parseResponse() — structured entries extracted from
 * a raw provider response. The optional `normalized` field holds a
 * JSON-safe representation for DAHR attestation (only for JSON providers;
 * XML/RSS providers are TLSN-only in Phase 4).
 */
export interface ParsedAdapterResponse {
  /** Structured entries extracted from the response */
  entries: EvidenceEntry[];
  /** JSON-normalized response (for DAHR-safe providers only) */
  normalized?: unknown;
}

// ── Candidate Validation ────────────────────────────

export interface CandidateValidation {
  /** Whether the candidate URL is valid for the requested attestation method */
  ok: boolean;
  /** Reason for rejection (if !ok) */
  reason?: string;
  /** Rewritten URL if validation corrected parameters (e.g., TLSN limit enforcement) */
  rewrittenUrl?: string;
}

// ── Build Context ───────────────────────────────────

export interface BuildCandidatesContext {
  /** Source record from catalog */
  source: SourceRecordV2;
  /** Topic string from the session */
  topic: string;
  /** Tokenized topic terms */
  tokens: string[];
  /** Template variables (asset, query, symbol, date, etc.) */
  vars: Record<string, string>;
  /** Attestation method to build candidates for */
  attestation: AttestationMethod;
  /** Max candidates to return */
  maxCandidates: number;
}

// ── Response Context ────────────────────────────────

export interface FetchedResponse {
  /** Fetched URL */
  url: string;
  /** HTTP status code */
  status: number;
  /** Response headers (lowercase keys) */
  headers: Record<string, string>;
  /** Response body as text */
  bodyText: string;
}

// ── Provider Adapter ────────────────────────────────

/**
 * Provider adapter — knows how to generate URLs, validate them for
 * attestation safety, and parse responses into structured evidence.
 *
 * Each adapter is a singleton registered in the provider registry.
 * Adapters do NOT own fetching — that's handled by fetch.ts.
 * Adapters do NOT own attestation — that's handled by publish-pipeline.ts.
 */
export interface ProviderAdapter {
  /** Provider identifier (must match catalog records' provider field) */
  readonly provider: string;
  /** Domains this provider covers (for logging/documentation) */
  readonly domains: string[];
  /** Rate limit declaration (enforced by rate-limit.ts, not the adapter) */
  readonly rateLimit: {
    /** Bucket key for rate limiting (typically provider name) */
    bucket: string;
    /** Max requests per minute (undefined = unlimited) */
    maxPerMinute?: number;
    /** Max requests per day (undefined = unlimited) */
    maxPerDay?: number;
  };

  /**
   * Check if this adapter supports a given source record.
   * Used by the registry to resolve adapter for a source.
   */
  supports(source: SourceRecordV2): boolean;

  /**
   * Generate concrete candidate URLs for a source+topic combination.
   * Returns multiple candidates ranked by relevance.
   * MUST produce only attestation-safe URLs for the requested method.
   */
  buildCandidates(ctx: BuildCandidatesContext): CandidateRequest[];

  /**
   * Validate a candidate URL before attestation.
   * Second guard after buildCandidates — checks URL parameters against
   * provider-specific constraints (e.g., TLSN response size limits).
   * May rewrite the URL to enforce safety (e.g., force hitsPerPage=2).
   */
  validateCandidate(candidate: CandidateRequest): CandidateValidation;

  /**
   * Parse a fetched response into structured evidence entries.
   * For JSON providers, also produces a normalized JSON representation.
   * For XML/RSS providers, parses into entries but no DAHR normalization
   * (Phase 4 rule: XML/RSS is TLSN-only for publish).
   */
  parseResponse(source: SourceRecordV2, response: FetchedResponse): ParsedAdapterResponse;

  /**
   * Build a surgical URL targeting a specific claim for attestation.
   * Returns a SurgicalCandidate if this provider can verify the claim, null otherwise.
   * Optional — only YAML specs with claimTypes produce this method.
   */
  buildSurgicalUrl?(claim: ExtractedClaim, source: SourceRecordV2): SurgicalCandidate | null;
}
