export {
  calculateExpectedScore,
  SCORE_BASE,
  SCORE_ATTESTATION,
  SCORE_CONFIDENCE,
  SCORE_LONG_TEXT,
  SCORE_ENGAGEMENT_T1,
  SCORE_ENGAGEMENT_T2,
  SCORE_MAX,
  ENGAGEMENT_T1_THRESHOLD,
  ENGAGEMENT_T2_THRESHOLD,
  LONG_TEXT_MIN_CHARS,
} from "../../lib/scoring/scoring.js";
