#!/usr/bin/env -S bunx tsx
/**
 * Profile Generator — assembles Claude Code agent profiles from persona files.
 *
 * Combines universal sections (scoring formula, phase CLI commands, TLSN gotchas)
 * with per-agent sections (identity from AGENT.yaml, voice from persona.md, config
 * from persona.yaml) into a complete profile at profiles/{name}-session.md.
 *
 * Usage:
 *   bunx tsx tools/generate-profile.ts --agent sentinel
 *   bunx tsx tools/generate-profile.ts --agent crawler
 *   bunx tsx tools/generate-profile.ts --all
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const PROFILES_DIR = resolve(REPO_ROOT, "profiles");
const AGENTS_DIR = resolve(REPO_ROOT, "agents");

// ── Arg Parsing ────────────────────────────────────

function parseArgs(): { agent?: string; all: boolean } {
  const args = process.argv.slice(2);
  let agent: string | undefined;
  let all = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--help" || args[i] === "-h") {
      console.log(`
Profile Generator — Claude Code agent profile assembler

USAGE:
  bunx tsx tools/generate-profile.ts --agent NAME
  bunx tsx tools/generate-profile.ts --all

FLAGS:
  --agent NAME   Generate profile for a specific agent
  --all          Generate profiles for all agents in agents/
  --help, -h     Show this help
`);
      process.exit(0);
    }
    if (args[i] === "--agent" && args[i + 1]) {
      agent = args[i + 1];
      i++;
    }
    if (args[i] === "--all") all = true;
  }

  if (!agent && !all) {
    console.error("Error: specify --agent NAME or --all");
    process.exit(1);
  }

  return { agent, all };
}

// ── File Loaders ───────────────────────────────────

function loadFile(path: string): string {
  if (!existsSync(path)) return "";
  return readFileSync(path, "utf-8");
}

// ── Universal Sections ─────────────────────────────

function universalSections(agentName: string): string {
  return `
## Scoring Formula (verified n=34)

| Component | Points | Condition |
|-----------|--------|-----------|
| Base | 20 | Every post |
| Attestation | 40 | DAHR or TLSN present |
| Confidence | 10 | confidence field set |
| Long text | 10 | Text > 200 characters |
| Engagement T1 | 10 | >= 5 total reactions |
| Engagement T2 | 10 | >= 15 total reactions |
| **Max** | **100** | |

Category is IRRELEVANT for scoring. Engagement tiers are purely reaction-count-based.

## Active Operator Commands

Use the package route for current operator work:

- \`bun run --cwd packages/omniweb-toolkit omniweb -- colony feed --limit 10\`
- \`bun run --cwd packages/omniweb-toolkit omniweb -- colony signals\`
- \`bun run --cwd packages/omniweb-toolkit run:colony-operator-cycle\`
- \`bun run --cwd packages/omniweb-toolkit check:colony-operator-cycle\`
- \`bun run --cwd packages/omniweb-toolkit check:colony-operator-entrypoint\`

## Error Recovery

- If a tool fails, check stderr output first
- Inspect package cycle artifacts and session ledger output
- State persists under the configured minimal-agent state and ledger dirs

## TLSN Gotchas

- TLSN notary URL from Demos node returns \`ws://\` — must convert to \`http://\`
- maxRecvData capped at 16384 (16KB)
- HN Algolia: always use \`hitsPerPage=2\` — responses with 5+ hits exceed 16KB
- TLSN runs in Web Worker (WASM) via Playwright bridge
- Cost: ~12 DEM per attestation (1 request + 11 storage)

## SDK Gotchas

- Runtime: Node.js + tsx (NOT bun — NAPI crash)
- DAHR \`startProxy()\` is the complete operation — no \`stopProxy()\`
- txHash is in CONFIRM response, NOT broadcast response
- Feed API returns object (not array) — extract posts with fallback chain
- \`reactions.agree\` (singular), NOT \`reactions.agrees\`
- Timestamps are Unix ms numbers, NOT ISO strings
`;
}

// ── Profile Assembly ───────────────────────────────

function generateProfile(agentName: string): string {
  const agentDir = resolve(AGENTS_DIR, agentName);
  if (!existsSync(agentDir)) {
    throw new Error(`Agent directory not found: ${agentDir}`);
  }

  const agentYaml = loadFile(resolve(agentDir, "AGENT.yaml"));
  const personaMd = loadFile(resolve(agentDir, "persona.md"));
  const strategyYaml = loadFile(resolve(agentDir, "strategy.yaml"));

  const lines: string[] = [];

  lines.push(`<!-- GENERATED by generate-profile.ts — do not edit manually -->`);
  lines.push(`<!-- Regenerate with: bunx tsx tools/generate-profile.ts --agent ${agentName} -->`);
  lines.push(``);
  lines.push(`# ${agentName.charAt(0).toUpperCase() + agentName.slice(1)} — SuperColony Agent Session Profile`);
  lines.push(``);

  // Identity section from AGENT.yaml
  if (agentYaml) {
    lines.push(`## Agent Definition`);
    lines.push(``);
    lines.push("```yaml");
    lines.push(agentYaml.trim());
    lines.push("```");
    lines.push(``);
  }

  // Voice & post guidelines from persona.md
  if (personaMd) {
    lines.push(`## Persona`);
    lines.push(``);
    lines.push(personaMd.trim());
    lines.push(``);
  }

  // Universal sections
  lines.push(universalSections(agentName));

  // Strategy reference
  if (strategyYaml) {
    lines.push(`## Strategy Reference`);
    lines.push(``);
    lines.push("```yaml");
    // Include first 60 lines of strategy for reference (not the whole thing)
    const strategyLines = strategyYaml.split("\n");
    const preview = strategyLines.slice(0, 60).join("\n");
    lines.push(preview);
    if (strategyLines.length > 60) {
      lines.push(`# ... ${strategyLines.length - 60} more lines — see agents/${agentName}/strategy.yaml`);
    }
    lines.push("```");
    lines.push(``);
  }

  return lines.join("\n");
}

// ── Main ───────────────────────────────────────────

function main(): void {
  const { agent, all } = parseArgs();

  mkdirSync(PROFILES_DIR, { recursive: true });

  const agents: string[] = [];
  if (all) {
    for (const entry of readdirSync(AGENTS_DIR, { withFileTypes: true })) {
      if (entry.isDirectory() && existsSync(resolve(AGENTS_DIR, entry.name, "AGENT.yaml"))) {
        agents.push(entry.name);
      }
    }
    if (agents.length === 0) {
      console.error("No agents found in agents/");
      process.exit(1);
    }
  } else if (agent) {
    agents.push(agent);
  }

  for (const name of agents) {
    const profile = generateProfile(name);
    const outPath = resolve(PROFILES_DIR, `${name}-session.md`);
    writeFileSync(outPath, profile);
    console.log(`Generated: ${outPath} (${profile.split("\n").length} lines)`);
  }
}

main();
