/**
 * Security Sentinel — External security data sources.
 *
 * Custom NVD/GHSA fetchers that supplement the compiler-generated observe.
 * These are NOT generated by the Agent Compiler — they're domain-specific
 * HTTP fetchers for external vulnerability databases.
 */
import type { AvailableEvidence } from "../../src/toolkit/colony/available-evidence.js";

const FETCH_TIMEOUT_MS = 10_000;

// ── External source URLs ───────────────────────
const NVD_URL = "https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=20";
const GITHUB_ADVISORIES_URL = "https://api.github.com/advisories?type=reviewed&severity=critical,high&per_page=10";

// ── NVD CVE → AvailableEvidence ────────────────

export interface NvdVulnerability {
  cve: {
    id: string;
    descriptions: Array<{ lang: string; value: string }>;
    metrics?: {
      cvssMetricV31?: Array<{ cvssData: { baseScore: number; baseSeverity: string } }>;
    };
  };
}

export function nvdToEvidence(vulns: NvdVulnerability[]): AvailableEvidence[] {
  return vulns.map(v => {
    const severity = v.cve.metrics?.cvssMetricV31?.[0]?.cvssData.baseSeverity ?? "UNKNOWN";
    const desc = v.cve.descriptions.find(d => d.lang === "en")?.value ?? "";
    return {
      sourceId: `nvd-${v.cve.id}`,
      subject: "security-vulnerability",
      metrics: [severity, v.cve.id],
      richness: desc.length,
      freshness: 0,
      stale: false,
    };
  });
}

// ── GitHub Advisory → AvailableEvidence ────────

export interface GhAdvisory {
  ghsa_id: string;
  summary: string;
  severity: string;
  html_url: string;
}

export function ghsaToEvidence(advisories: GhAdvisory[]): AvailableEvidence[] {
  return advisories.map(a => ({
    sourceId: `ghsa-${a.ghsa_id}`,
    subject: "security-advisory",
    metrics: [a.severity, a.ghsa_id],
    richness: a.summary.length,
    freshness: 0,
    stale: false,
  }));
}

// ── External fetchers (try/catch + AbortSignal.timeout) ──

export async function fetchNvd(): Promise<AvailableEvidence[]> {
  try {
    const res = await fetch(NVD_URL, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
    if (!res.ok) return [];
    const data = await res.json() as { vulnerabilities?: NvdVulnerability[] };
    return nvdToEvidence(data.vulnerabilities ?? []);
  } catch {
    return [];
  }
}

export async function fetchGhsa(): Promise<AvailableEvidence[]> {
  try {
    const res = await fetch(GITHUB_ADVISORIES_URL, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
    if (!res.ok) return [];
    const data = await res.json() as GhAdvisory[];
    return ghsaToEvidence(Array.isArray(data) ? data : []);
  } catch {
    return [];
  }
}
