import type { RuntimeCapabilityResult } from "./readiness.js";

export function buildInjectedRuntimeCapabilities(): RuntimeCapabilityResult {
  return {
    canRead: true,
    authReady: true,
    writeReady: true,
    recommendedMode: "write-ready",
    blockers: [],
    actionFamilies: {
      publish: {
        declared: true,
        executable: true,
        readiness: "ready",
        requiresWallet: true,
        requiresAttestation: true,
        requiresTargetPost: false,
        requiresMarketContext: false,
        proofLevel: "real_runtime_action_family",
        notes: ["Injected omni session bypasses file-based readiness discovery"],
      },
      reply: {
        declared: true,
        executable: true,
        readiness: "ready",
        requiresWallet: true,
        requiresAttestation: true,
        requiresTargetPost: true,
        requiresMarketContext: false,
        proofLevel: "real_runtime_action_family",
        notes: ["Injected omni session bypasses file-based readiness discovery"],
      },
      react: {
        declared: true,
        executable: true,
        readiness: "ready",
        requiresWallet: true,
        requiresAttestation: false,
        requiresTargetPost: true,
        requiresMarketContext: false,
        proofLevel: "real_runtime_action_family",
        notes: ["Injected omni session bypasses file-based readiness discovery"],
      },
      tip: {
        declared: true,
        executable: true,
        readiness: "ready",
        requiresWallet: true,
        requiresAttestation: false,
        requiresTargetPost: true,
        requiresMarketContext: false,
        proofLevel: "real_runtime_action_family",
        notes: ["Injected omni session bypasses file-based readiness discovery for live tip execution"],
      },
      bet: {
        declared: true,
        executable: true,
        readiness: "ready",
        requiresWallet: true,
        requiresAttestation: false,
        requiresTargetPost: false,
        requiresMarketContext: true,
        proofLevel: "real_runtime_action_family",
        notes: ["Injected omni session executes bet actions through placeBet()/placeHL() with shared market-pool verification"],
      },
    },
    readiness: {
      ok: true,
      canRead: true,
      canAuth: true,
      canWrite: true,
      authState: "ready",
      writeState: "ready",
      missingEnv: [],
      missingPackages: [],
      credentialSourcesChecked: [],
      runtimeCredentialSource: null,
      notes: ["Injected omni session bypasses file-based readiness discovery"],
    },
  };
}
