#!/usr/bin/env npx tsx
/**
 * Session Report Viewer — list and display saved session reports.
 *
 * Reports are written by session-runner.ts on completion to:
 *   ~/.sentinel/sessions/session-{N}-report.md
 *
 * Usage:
 *   npx tsx tools/session-report.ts --list          # List all reports
 *   npx tsx tools/session-report.ts 7               # Display session 7 report
 *   npx tsx tools/session-report.ts --latest         # Display most recent report
 */

import { resolve } from "node:path";
import { readdirSync, readFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { resolveAgentName, loadAgentConfig } from "./lib/agent-config.js";

// Agent resolved at runtime (after arg parsing)
let SESSIONS_DIR = resolve(homedir(), ".sentinel", "sessions");
const REPORT_PATTERN = /^session-(\d+)-report\.md$/;

interface ReportMeta {
  sessionNumber: number;
  path: string;
  firstLine: string;
}

function findReports(): ReportMeta[] {
  if (!existsSync(SESSIONS_DIR)) return [];

  const reports: ReportMeta[] = [];
  for (const f of readdirSync(SESSIONS_DIR)) {
    const match = f.match(REPORT_PATTERN);
    if (!match) continue;
    const path = resolve(SESSIONS_DIR, f);
    try {
      const content = readFileSync(path, "utf-8");
      const firstLine = content.split("\n")[0] || f;
      reports.push({ sessionNumber: Number(match[1]), path, firstLine });
    } catch {
      // Skip unreadable files
      reports.push({ sessionNumber: Number(match[1]), path, firstLine: `(unreadable: ${f})` });
    }
  }
  return reports.sort((a, b) => a.sessionNumber - b.sessionNumber);
}

function listReports(): void {
  const reports = findReports();
  if (reports.length === 0) {
    console.log("No session reports found.");
    console.log(`Reports are generated by session-runner.ts in ${SESSIONS_DIR}`);
    return;
  }

  console.log(`\n  SESSION REPORTS (${SESSIONS_DIR})\n`);
  console.log("  #     Title");
  console.log("  " + "─".repeat(60));
  for (const r of reports) {
    const title = r.firstLine.replace(/^#+\s*/, "");
    console.log(`  ${String(r.sessionNumber).padStart(3)}   ${title}`);
  }
  console.log();
}

function showReport(sessionNumber: number): void {
  const reportPath = resolve(SESSIONS_DIR, `session-${sessionNumber}-report.md`);
  if (!existsSync(reportPath)) {
    console.error(`No report found for session ${sessionNumber}.`);
    console.error(`Expected: ${reportPath}`);
    process.exit(1);
  }
  console.log(readFileSync(reportPath, "utf-8"));
}

function showLatest(): void {
  const reports = findReports();
  if (reports.length === 0) {
    console.log("No session reports found.");
    return;
  }
  const latest = reports[reports.length - 1];
  console.log(readFileSync(latest.path, "utf-8"));
}

// ── Main ──────────────────────────────────────────

const args = process.argv.slice(2);

// Resolve agent name and update sessions dir
{
  const flags: Record<string, string> = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--agent" && args[i + 1]) {
      flags["agent"] = args[i + 1];
    }
  }
  const agentName = resolveAgentName(flags);
  const config = loadAgentConfig(agentName);
  SESSIONS_DIR = config.paths.sessionDir;
}

if (args.includes("--help") || args.includes("-h")) {
  console.log(`
Session Report Viewer

USAGE:
  npx tsx tools/session-report.ts --list          List all session reports
  npx tsx tools/session-report.ts <N>             Display report for session N
  npx tsx tools/session-report.ts --latest        Display most recent report
  npx tsx tools/session-report.ts --help          Show this help
`);
  process.exit(0);
}

if (args.includes("--list")) {
  listReports();
} else if (args.includes("--latest")) {
  showLatest();
} else {
  // Find first positional arg (non-flag, not a flag value)
  // Only these flags consume a value; all others are boolean
  const VALUE_FLAGS = new Set(["--agent", "--env"]);
  let sessionNum: number | null = null;
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith("--")) {
      // Skip flag; only consume next arg if this flag takes a value
      if (VALUE_FLAGS.has(args[i]) && args[i + 1]) i++;
      continue;
    }
    if (/^\d+$/.test(args[i])) {
      sessionNum = Number(args[i]);
      break;
    }
  }
  if (sessionNum !== null) {
    showReport(sessionNum);
  } else {
    // Default: show list
    listReports();
  }
}
